CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
    currency VARCHAR(3) NOT NULL DEFAULT 'PLN',
    expense_date DATE NOT NULL,
    category VARCHAR(32) NOT NULL CHECK (
        category IN (
            'GROCERIES', 'DINING_OUT', 'TRANSPORT', 'HOUSING', 'UTILITIES',
            'HEALTH', 'ENTERTAINMENT', 'SHOPPING', 'TRAVEL', 'EDUCATION',
            'PERSONAL_CARE', 'OTHER'
        )
    ),
    note TEXT
);

CREATE INDEX idx_expenses_expense_date ON expenses (expense_date);
