CREATE TABLE incomes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
    currency VARCHAR(3) NOT NULL DEFAULT 'PLN',
    income_date DATE NOT NULL,
    source VARCHAR(32) NOT NULL CHECK (
        source IN (
            'SALARY', 'FREELANCE_SIDE_INCOME', 'GIFT', 'REFUND',
            'INVESTMENT_RETURN', 'OTHER'
        )
    ),
    note TEXT
);

CREATE INDEX idx_incomes_income_date ON incomes (income_date);
